// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppAbout: typeof import('./src/components/AppAbout.vue')['default']
    AppHome: typeof import('./src/components/AppHome.vue')['default']
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    AppTips: typeof import('./src/components/AppTips.vue')['default']
    ArrowLeft: typeof import('./src/components/icons/ArrowLeft.vue')['default']
    ArrowRight: typeof import('./src/components/icons/ArrowRight.vue')['default']
    ChevronUp: typeof import('./src/components/icons/ChevronUp.vue')['default']
    Dark: typeof import('./src/components/icons/Dark.vue')['default']
    DarkMode: typeof import('./.vitepress/theme/DarkMode.vue')['default']
    Github: typeof import('./src/components/icons/Github.vue')['default']
    Instagram: typeof import('./src/components/icons/Instagram.vue')['default']
    Layout: typeof import('./.vitepress/theme/Layout.vue')['default']
    Light: typeof import('./src/components/icons/Light.vue')['default']
    Linkedin: typeof import('./src/components/icons/Linkedin.vue')['default']
    PostMeta: typeof import('./src/components/PostMeta.vue')['default']
    PostPreview: typeof import('./src/components/PostPreview.vue')['default']
    PostScrollTop: typeof import('./src/components/PostScrollTop.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}

export { }
